### ISSUE TITLE
Example 2 not working

### ISSUE THREAD

**Issue by dbof10** [jlfwong/graphics-experiments#1]
I compile `particle2` with cmd `tsc *.ts`. The HTML file shows empty page

**Comment by jlfwong** [comment]
Oh, hah -- this code was just somewhere for me to dump this stuff, and was never intended to be consumed by anyone else. I'm not surprised it doesn't work, but this also isn't something that I intend to maintain or review pull requests for. Feel free to pull stuff out of here if it's useful to you, but otherwise this isn't a maintained codebase
